export const DTL_STATIONS = [
  { code: "DT1", name: "Bukit Panjang" },
  { code: "DT2", name: "Cashew" },
  { code: "DT3", name: "Hillview" },
  { code: "DT4", name: "Hume" },
  { code: "DT5", name: "Beauty World" },
  { code: "DT6", name: "King Albert Park" },
  { code: "DT7", name: "Sixth Avenue" },
  { code: "DT8", name: "Tan Kah Kee" },
  { code: "DT9", name: "Botanic Gardens" },
  { code: "DT10", name: "Stevens" },
  { code: "DT11", name: "Newton" },
  { code: "DT12", name: "Little India" },
  { code: "DT13", name: "Rochor" },
  { code: "DT14", name: "Bugis" },
  { code: "DT15", name: "Promenade" },
  { code: "DT16", name: "Bayfront" },
  { code: "DT17", name: "Downtown" },
  { code: "DT18", name: "Telok Ayer" },
  { code: "DT19", name: "Chinatown" },
  { code: "DT20", name: "Fort Canning" },
  { code: "DT21", name: "Bencoolen" },
  { code: "DT22", name: "Jalan Besar" },
  { code: "DT23", name: "Bendemeer" },
  { code: "DT24", name: "Geylang Bahru" },
  { code: "DT25", name: "Mattar" },
  { code: "DT26", name: "MacPherson" },
  { code: "DT27", name: "Ubi" },
  { code: "DT28", name: "Kaki Bukit" },
  { code: "DT29", name: "Bedok North" },
  { code: "DT30", name: "Bedok Reservoir" },
  { code: "DT31", name: "Tampines West" },
  { code: "DT32", name: "Tampines" },
  { code: "DT33", name: "Tampines East" },
  { code: "DT34", name: "Upper Changi" },
  { code: "DT35", name: "Expo" },
] as const;

export const DTL_EDGES = DTL_STATIONS.slice(0, -1).map((station, index) => ({
  from: station.code,
  to: DTL_STATIONS[index + 1].code,
  weight: 3,
}));
