
// arrays of objects with code key and name key
 export const EWL_STATIONS = [ // export = data is accessible in other files
  // Main Line
  { code: "EW1",  name: "Pasir Ris" },
  { code: "EW2",  name: "Tampines" },
  { code: "EW3",  name: "Simei" },
  { code: "EW4",  name: "Tanah Merah" },
  { code: "EW5",  name: "Bedok" },
  { code: "EW6",  name: "Kembangan" },
  { code: "EW7",  name: "Eunos" },
  { code: "EW8",  name: "Paya Lebar" },
  { code: "EW9",  name: "Aljunied" },
  { code: "EW10", name: "Kallang" },
  { code: "EW11", name: "Lavender" },
  { code: "EW12", name: "Bugis" },
  { code: "EW13", name: "City Hall" },
  { code: "EW14", name: "Raffles Place" },
  { code: "EW15", name: "Tanjong Pagar" },
  { code: "EW16", name: "Outram Park" },
  { code: "EW17", name: "Tiong Bahru" },
  { code: "EW18", name: "Redhill" },
  { code: "EW19", name: "Queenstown" },
  { code: "EW20", name: "Commonwealth" },
  { code: "EW21", name: "Buona Vista" },
  { code: "EW22", name: "Dover" },
  { code: "EW23", name: "Clementi" },
  { code: "EW24", name: "Jurong East" },
  { code: "EW25", name: "Chinese Garden" },
  { code: "EW26", name: "Lakeside" },
  { code: "EW27", name: "Boon Lay" },
  { code: "EW28", name: "Pioneer" },
  { code: "EW29", name: "Joo Koon" },
  { code: "EW30", name: "Gul Circle" },
  { code: "EW31", name: "Tuas Crescent" },
  { code: "EW32", name: "Tuas West Road" },
  { code: "EW33", name: "Tuas Link" },

  // Changi Airport Branch
  { code: "CG1",  name: "Expo" },
  { code: "CG2",  name: "Changi Airport" },
] as const;
export type EWLStationCode = typeof EWL_STATIONS[number]["code"];
// arrays of objects with from, to, and weight keys
export const EWL_EDGES = [
  { from: "EW1",  to: "EW2",  weight: 3 },
  { from: "EW2",  to: "EW3",  weight: 3 },
  { from: "EW3",  to: "EW4",  weight: 3 },
  { from: "EW4",  to: "EW5",  weight: 4 },
  { from: "EW5",  to: "EW6",  weight: 3 },
  { from: "EW6",  to: "EW7",  weight: 2 },
  { from: "EW7",  to: "EW8",  weight: 3 },
  { from: "EW8",  to: "EW9",  weight: 3 },
  { from: "EW9",  to: "EW10", weight: 2 },
  { from: "EW10", to: "EW11", weight: 2 },
  { from: "EW11", to: "EW12", weight: 2 },
  { from: "EW12", to: "EW13", weight: 2 },
  { from: "EW13", to: "EW14", weight: 1 },
  { from: "EW14", to: "EW15", weight: 2 },
  { from: "EW15", to: "EW16", weight: 2 },
  { from: "EW16", to: "EW17", weight: 2 },
  { from: "EW17", to: "EW18", weight: 2 },
  { from: "EW18", to: "EW19", weight: 2 },
  { from: "EW19", to: "EW20", weight: 2 },
  { from: "EW20", to: "EW21", weight: 2 },
  { from: "EW21", to: "EW22", weight: 3 },
  { from: "EW22", to: "EW23", weight: 3 },
  { from: "EW23", to: "EW24", weight: 4 },
  { from: "EW24", to: "EW25", weight: 3 },
  { from: "EW25", to: "EW26", weight: 2 },
  { from: "EW26", to: "EW27", weight: 3 },
  { from: "EW27", to: "EW28", weight: 3 },
  { from: "EW28", to: "EW29", weight: 3 },
  { from: "EW29", to: "EW30", weight: 4 },
  { from: "EW30", to: "EW31", weight: 4 },
  { from: "EW31", to: "EW32", weight: 3 },
  { from: "EW32", to: "EW33", weight: 4 },

  // Changi branch
  { from: "EW4",  to: "CG1",  weight: 5 },
  { from: "CG1",  to: "CG2",  weight: 4 },
] as const;
